services:
  api:
    build: .
    container_name: api_argus
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_PORT: ${API_PORT}
      CORS_ORIGIN_PATTERNS: ${CORS_ORIGIN_PATTERNS}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres

  postgres:
    image: postgres:17 
    container_name: postgres_argus
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    ports:
      - 5432:5432