spring:
    application:  
        name: argus

    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}

app:
  cors:
    corsOriginPatterns: ${CORS_ORIGIN_PATTERNS}

springdoc:
  swagger-ui:
    use-root-path: true

server:
  port: ${API_PORT}